# backend/init_db.py
import sqlite3
import os

def init_database():
    """Inicializa o banco SQLite com os dados do seed.sql"""
    db_path = "wisesales.db"
    
    # Remover banco existente se houver
    if os.path.exists(db_path):
        os.remove(db_path)
    
    # Ler o arquivo seed.sql
    with open('../seed.sql', 'r') as file:
        sql_script = file.read()
    
    # Adaptar SQL de PostgreSQL para SQLite
    # Remover comandos específicos do PostgreSQL
    sql_script = sql_script.replace('SERIAL', 'INTEGER PRIMARY KEY AUTOINCREMENT')
    sql_script = sql_script.replace('INT GENERATED BY DEFAULT AS IDENTITY', 'INTEGER')
    sql_script = sql_script.replace('NOW()', "datetime('now')")
    
    # Conectar e executar script
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # Executar cada comando separadamente
    for statement in sql_script.split(';'):
        if statement.strip():
            try:
                cursor.execute(statement)
            except sqlite3.Error as e:
                print(f"Erro na execução: {e}")
                print(f"Statement: {statement}")
    
    conn.commit()
    conn.close()
    print("✅ Banco SQLite inicializado com sucesso!")

if __name__ == "__main__":
    init_database()